update for release 4, rename jboss to tomcat

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -2,7 +2,7 @@
 set -e
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
-source ${OPENSHIFT_JBOSSEWS_DIR}/bin/util
+source ${OPENSHIFT_TOMCAT_DIR}/bin/util
 
 if ! [ $# -eq 1 ]
 then
@@ -10,9 +10,9 @@ then
     exit 1
 fi
 
-cartridge_type="jbossews"
+cartridge_type="tomcatews"
 
-JBOSS_PID_FILE="${OPENSHIFT_JBOSSEWS_DIR}/run/jboss.pid"
+TOMCAT_PID_FILE="${OPENSHIFT_TOMCAT_DIR}/run/tomcat.pid"
 
 # Kill the process given by $1 and its children
 killtree() {
@@ -24,11 +24,11 @@ killtree() {
     kill -9 ${_pid}
 }
 
-# Check if the jbossas process is running
+# Check if the tomcatas process is running
 isrunning() {
     # Check for running app
-    if [ -f "$JBOSS_PID_FILE" ]; then
-      jbpid=$(cat $JBOSS_PID_FILE);
+    if [ -f "$TOMCAT_PID_FILE" ]; then
+      jbpid=$(cat $TOMCAT_PID_FILE);
       running=`/bin/ps --no-headers --pid $jbpid`
       if test -n "$running";
       then
@@ -44,13 +44,13 @@ function ishttpup() {
     count=0
     while [ ${count} -lt 64 ]
     do
-        if /usr/sbin/lsof -P -n -i "@${OPENSHIFT_JBOSSEWS_IP}:${OPENSHIFT_JBOSSEWS_HTTP_PORT}" | grep "(LISTEN)" > /dev/null; then
-            echo "Found ${OPENSHIFT_JBOSSEWS_IP}:${OPENSHIFT_JBOSSEWS_HTTP_PORT} listening port"
+        if /usr/sbin/lsof -P -n -i "@${OPENSHIFT_TOMCAT_IP}:${OPENSHIFT_TOMCAT_HTTP_PORT}" | grep "(LISTEN)" > /dev/null; then
+            echo "Found ${OPENSHIFT_TOMCAT_IP}:${OPENSHIFT_TOMCAT_HTTP_PORT} listening port"
             return 0
         fi
         # if the process failed to start, error out immediately
         # rather than waiting for the timeout on the port being available.
-        jbpid=$(cat $JBOSS_PID_FILE);
+        jbpid=$(cat $TOMCAT_PID_FILE);
         if ! ps | grep -v grep | grep $jbpid > /dev/null; then
           return 2
         fi
@@ -64,9 +64,9 @@ function ishttpup() {
 function start_app() {
     # Check for running app
     if isrunning; then
-        echo "The jbossews cartridge is already running" 1>&2
+        echo "The tomcatews cartridge is already running" 1>&2
     else
-        echo "Starting jbossews cartridge"
+        echo "Starting tomcatews cartridge"
         
         # Setup the config directory (for --from-code path where the code repository did
         # not provide config files, link to the template config files)
@@ -83,16 +83,16 @@ function start_app() {
         done
         
         # Start
-        export CATALINA_HOME=$OPENSHIFT_JBOSSEWS_DIR
-        export CATALINA_BASE=$OPENSHIFT_JBOSSEWS_DIR
-        export CATALINA_TMPDIR=${OPENSHIFT_JBOSSEWS_DIR}/tmp
+        export CATALINA_HOME=$OPENSHIFT_TOMCAT_DIR
+        export CATALINA_BASE=$OPENSHIFT_TOMCAT_DIR
+        export CATALINA_TMPDIR=${OPENSHIFT_TOMCAT_DIR}/tmp
 
-        LOGPIPE=${OPENSHIFT_HOMEDIR}/app-root/runtime/logshifter-jbossews
+        LOGPIPE=${OPENSHIFT_HOMEDIR}/app-root/runtime/logshifter-tomcatews
         rm -f $LOGPIPE && mkfifo $LOGPIPE
 
-        /usr/bin/logshifter -tag jbossews < $LOGPIPE &
-        ${OPENSHIFT_JBOSSEWS_DIR}/bin/tomcat start &> $LOGPIPE &
-        echo $! > $JBOSS_PID_FILE
+        /usr/bin/logshifter -tag tomcatews < $LOGPIPE &
+        ${OPENSHIFT_TOMCAT_DIR}/bin/tomcat start &> $LOGPIPE &
+        echo $! > $TOMCAT_PID_FILE
 
         rc=0
         ishttpup || rc=$?
@@ -108,39 +108,39 @@ function start_app() {
 
 function stop_app() {
     if ! isrunning; then
-        echo "The jbossews cartridge is already stopped" 1>&2
-    elif [ -f "$JBOSS_PID_FILE" ]; then
-        echo "Stopping jbossews cartridge"
-        pid=$(cat $JBOSS_PID_FILE);
-        echo "Sending SIGTERM to jboss:$pid ..." 1>&2
+        echo "The tomcatews cartridge is already stopped" 1>&2
+    elif [ -f "$TOMCAT_PID_FILE" ]; then
+        echo "Stopping tomcatews cartridge"
+        pid=$(cat $TOMCAT_PID_FILE);
+        echo "Sending SIGTERM to tomcat:$pid ..." 1>&2
         killtree $pid
     else 
-        echo "Failed to locate JBOSS PID File" 1>&2
+        echo "Failed to locate TOMCAT PID File" 1>&2
     fi
 }
 
 function threaddump() {
     if ! isrunning; then
-        echo "The jbossews cartridge is stopped"
+        echo "The tomcatews cartridge is stopped"
         exit 1
-    elif [ -f "$JBOSS_PID_FILE" ]; then
-        pid=$(cat $JBOSS_PID_FILE);
+    elif [ -f "$TOMCAT_PID_FILE" ]; then
+        pid=$(cat $TOMCAT_PID_FILE);
         java_pid=`ps h --ppid $pid -o '%p'`
         kill -3 $java_pid
         client_result "Success"
         client_result ""        
         client_result "The thread dump file will be available via: rhc tail $OPENSHIFT_APP_NAME -g $OPENSHIFT_GEAR_UUID -f ${OPENSHIFT_LOG_DIR}${cartridge_type}.log -o '-n 250'"
     else 
-        echo "Failed to locate JBOSS PID File"
+        echo "Failed to locate TOMCAT PID File"
     fi
 }
 
 # Clean up any log files
 function tidy() {
-  client_message "Emptying jbossews logs from dir: $OPENSHIFT_LOG_DIR"
+  client_message "Emptying tomcatews logs from dir: $OPENSHIFT_LOG_DIR"
   shopt -s dotglob
-  rm -rf $OPENSHIFT_LOG_DIR/jbossews.log*
-  rm -rf $OPENSHIFT_JBOSSEWS_DIR/tmp/*
+  rm -rf $OPENSHIFT_LOG_DIR/tomcatews.log*
+  rm -rf $OPENSHIFT_TOMCAT_DIR/tmp/*
 }
 
 # Reconstruct JAVA_HOME and PATH based on the current version/marker selection
@@ -177,15 +177,15 @@ case "$1" in
             exit 0
         fi
 
-        client_result "The jbossews cartridge is running."
+        client_result "The tomcatews cartridge is running."
         exit 0
     ;;
     build)
-        ${OPENSHIFT_JBOSSEWS_DIR}/bin/build
+        ${OPENSHIFT_TOMCAT_DIR}/bin/build
         exit 0
     ;;
     deploy)
-        ${OPENSHIFT_JBOSSEWS_DIR}/bin/deploy
+        ${OPENSHIFT_TOMCAT_DIR}/bin/deploy
         exit 0
     ;;
     update-configuration)
