rename tomcatews -> tomcat

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -13,13 +13,13 @@ if [ ! -d "$SYSTEM_TOMCAT_DIR" ]; then
   rm -fr "${SYSTEM_TOMCAT_DIR}*"
   pushd "${OPENSHIFT_DATA_DIR}"
   if [ "${version}" == "6.0" ]; then
-    VERSION="6.0.39"
+    VERSION="6.0.41"
     wget "http://psg.mtu.edu/pub/apache/tomcat/tomcat-6/v${VERSION}/bin/apache-tomcat-${VERSION}.tar.gz"
     tar xvzf ${OPENSHIFT_DATA_DIR}/apache-tomcat-${VERSION}.tar.gz
     rm -f ${OPENSHIFT_DATA_DIR}/apache-tomcat-${VERSION}.tar.gz
     ln -s ${OPENSHIFT_DATA_DIR}/apache-tomcat-${VERSION} ${OPENSHIFT_DATA_DIR}/apache-tomcat-6.0
   else
-    VERSION="7.0.53"
+    VERSION="7.0.54"
     wget "http://psg.mtu.edu/pub/apache/tomcat/tomcat-7/v${VERSION}/bin/apache-tomcat-${VERSION}.tar.gz"
     tar xvzf ${OPENSHIFT_DATA_DIR}/apache-tomcat-${VERSION}.tar.gz
     rm -f ${OPENSHIFT_DATA_DIR}/apache-tomcat-${VERSION}.tar.gz
@@ -29,7 +29,7 @@ if [ ! -d "$SYSTEM_TOMCAT_DIR" ]; then
 fi
 
 if [ ! -d ${SYSTEM_TOMCAT_DIR} ]; then
-  echo "Couldn't find system tomcatews dir at ${SYSTEM_TOMCAT_DIR}" 1>&2
+  echo "Couldn't find system tomcat dir at ${SYSTEM_TOMCAT_DIR}" 1>&2
   exit 127
 fi
 
